apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: "demo-config-watcher"
data:
  application.yml: |-
    management:
      endpoint:
        env:
          enabled: true
          show-values: ALWAYS
        refresh:
          enabled: true
        restart:
          enabled: true
      endpoints:
        web:
          exposure:
            include: '*'
    spring:
      cloud:
        kubernetes:
          reload:
            enabled: true
          secrets:
            paths: /etc/secrets/db-secret
    mydata:
      name: William Clark
      email: williamc@yahoo.com
    