apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
  labels:
    spring.cloud.kubernetes.secret: "true"
  annotations:
    spring.cloud.kubernetes.secret.apps: "demo-config-watcher"
type: Opaque    
data:
  mysecrets.password: TWF5MzF0aDIwMjQ=
  mysecrets.username: enVsaUBnbWFpbC5jb20=